INSERT INTO projects VALUES (1, "project1", "category1", 10,  "June", "December");
INSERT INTO projects VALUES (2, "project2", "category2", 10,  "June", "December");
INSERT INTO projects VALUES (3, "project3", "category3", 10,  "June", "December");
INSERT INTO projects VALUES (4, "project4", "category4", 10,  "June", "December");
INSERT INTO projects VALUES (5, "project5", "category5", 10,  "June", "December");
INSERT INTO projects VALUES (6, "project6", "category6", 10,  "June", "December");
INSERT INTO projects VALUES (7, "project7", "category7", 10,  "June", "December");
INSERT INTO projects VALUES (8, "project8", "category8", 10,  "June", "December");
INSERT INTO projects VALUES (9, "project9", "category9", 10,  "June", "December");
INSERT INTO projects VALUES (10, "project10", "category10", 10,  "June", "December");

INSERT INTO users VALUES (1, "Dave", 20);
INSERT INTO users VALUES (2, "Jim", 46);
INSERT INTO users VALUES (3, "Steve", 32);
INSERT INTO users VALUES (4, "Roger", 70);
INSERT INTO users VALUES (5, "Kyle", 28);
INSERT INTO users VALUES (6, "Jeff", 30);
INSERT INTO users VALUES (7, "David", 32);
INSERT INTO users VALUES (8, "Edward", 12);
INSERT INTO users VALUES (9, "Lantz", 57);
INSERT INTO users VALUES (10, "Kaleb", 64);
INSERT INTO users VALUES (11, "Carter", 43);
INSERT INTO users VALUES (12, "Tucker", 54);
INSERT INTO users VALUES (13, "John", 23);
INSERT INTO users VALUES (14, "James", 34);
INSERT INTO users VALUES (15, "Joseph", 14);
INSERT INTO users VALUES (16, "Alex", 19);
INSERT INTO users VALUES (17, "Hunter", 45);
INSERT INTO users VALUES (18, "Joe", 32);
INSERT INTO users VALUES (19, "Smith", 67);
INSERT INTO users VALUES (20, "Salo", 73);


INSERT INTO pledges VALUES (1, 20, 1, 1);
INSERT INTO pledges VALUES (2, 20, 1, 1);
INSERT INTO pledges VALUES (3, 20, 1, 1);
INSERT INTO pledges VALUES (4, 20, 1, 1);
INSERT INTO pledges VALUES (5, 20, 1, 1);
INSERT INTO pledges VALUES (6, 20, 1, 1);
INSERT INTO pledges VALUES (7, 20, 1, 1);
INSERT INTO pledges VALUES (8, 20, 1, 1);
INSERT INTO pledges VALUES (9, 20, 1, 1);
INSERT INTO pledges VALUES (10, 20, 1, 1);
INSERT INTO pledges VALUES (11, 20, 1, 1);
INSERT INTO pledges VALUES (12, 20, 1, 1);
INSERT INTO pledges VALUES (13, 20, 1, 1);
INSERT INTO pledges VALUES (14, 20, 1, 1);
INSERT INTO pledges VALUES (15, 20, 1, 1);
INSERT INTO pledges VALUES (16, 20, 1, 1);
INSERT INTO pledges VALUES (17, 20, 1, 1);
INSERT INTO pledges VALUES (18, 20, 1, 1);
INSERT INTO pledges VALUES (19, 20, 1, 1);
INSERT INTO pledges VALUES (20, 20, 1, 1);
INSERT INTO pledges VALUES (21, 20, 1, 1);
INSERT INTO pledges VALUES (22, 20, 1, 1);
INSERT INTO pledges VALUES (23, 20, 1, 1);
INSERT INTO pledges VALUES (24, 20, 1, 1);
INSERT INTO pledges VALUES (25, 20, 1, 1);
INSERT INTO pledges VALUES (26, 20, 1, 1);
INSERT INTO pledges VALUES (27, 20, 1, 1);
INSERT INTO pledges VALUES (28, 20, 1, 1);
INSERT INTO pledges VALUES (29, 20, 1, 1);
INSERT INTO pledges VALUES (30, 20, 1, 1);